### PR TITLE
Fix RS256 token verification

### LINKED ISSUE #13: RS256 token verification does not work
If the token is signed with RS256, the third step (Verify User Token) seems to fail at verifying it. Can be verified by going to jwt.io and pasting the certificate.

screen shot 2016-10-12 at 11 58 17 am

### PR DESCRIPTION
**Pull request by twistedstream**
Closes #13 

This PR fixes the `/validation` endpoint so it properly supports RS256 validation of the `id_token`. The issues with the previous code:
1. It was bypassing RS256 verification altogether if `server` = `Auth0`
2. It wasn't properly examining the keys returned by the `/.well-known/jwks.json` endpoint, matching a key based on the `kid`

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -1,22 +1,18 @@
-'use strict'
+const express = require('express');
+const session = require('express-session');
+const crypto = require('crypto');
+const request = require('request');
+const jwt = require('jsonwebtoken');
+const jwkToPem = require('jwk-to-pem');
+require('dotenv').config();
```
Comment (alejofernandez) [inline index.js]: Could you please change this line to `require('dotenv').config({silent: true});` (I know it was already that way, but reviewing the code I just realized that if we don't have a `.dotenv` file it will throw an exception)
